version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: controle_financeiro_dev

  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db/controle_financeiro_dev
    depends_on:
      - db
    volumes:
      - .:/app
